@extends('common')
@include('geotags',['geotags'=>$geotags])
@include('menu')
@include('pagination',['$pagination_bar'=>$pagination_bar])
@include('showcase')
@include('pagination',['$pagination_bar'=>$pagination_bar])
